In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [26]:
# =========================================================
# USER INPUT FILES
# =========================================================
LINE_FILE = r"F:\P-52797\PS 694 Companiganj Noakhali\GeoJasionFile\ThalweghLine.geojson"
SURVEY_FILE = r"F:\P-52797\PS 694 Companiganj Noakhali\GeoJasionFile\XS_from_Nak_Geojason.geojson"
OUTPUT_FILE = r"F:\P-52797\PS 694 Companiganj Noakhali\GeoJasionFile\Thalweg_3m_Points_RL.geojson"

# =========================================================
# 1. LOAD DATA
# =========================================================
line_gdf = gpd.read_file(LINE_FILE)
survey_gdf = gpd.read_file(SURVEY_FILE)

# Ensure same CRS (must be projected in meters)
survey_gdf = survey_gdf.to_crs(line_gdf.crs)

In [27]:
line_gdf.head(10)

   id                                           geometry
0   1  MULTILINESTRING ((329938.261 2535991.391, 3296...
1   2  MULTILINESTRING ((329932.351 2536006.28, 32976...
2   3  MULTILINESTRING ((329950 2535964, 329797 25358...

In [28]:
survey_gdf.head(10)

,Chainage,X,Y,Distance_m,RL_mMSL,Remarks,geometry
0,17240.0,330099.053,2531693.153,0.0,2.534,None,POINT (330099.053 2531693.153)
1,17240.0,330095.718,2531696.106,4.0,2.645,None,POINT (330095.718 2531696.106)
2,17240.0,330094.526,2531698.458,7.0,2.731,None,POINT (330094.526 2531698.458)
3,17240.0,330093.971,2531702.576,11.0,2.679,None,POINT (330093.971 2531702.576)
4,17240.0,330093.838,2531704.391,12.0,2.698,None,POINT (330093.838 2531704.391)
5,17240.0,330091.303,2531706.929,16.0,2.639,None,POINT (330091.303 2531706.929)
6,17240.0,330089.193,2531709.086,19.0,2.464,None,POINT (330089.193 2531709.086)
7,17240.0,330087.369,2531710.838,21.0,2.395,None,POINT (330087.369 2531710.838)
8,17240.0,330085.950,2531712.982,24.0,2.424,None,POINT (330085.95 2531712.982)
9,17240.0,330083.956,2531715.124,27.0,2.514,None,POINT (330083.956 2531715.124)

In [29]:
INTERVAL = 3        # meters
BUFFER_DIST = 3     # meters

# =========================================================
# 2. FUNCTION: CREATE POINTS ALONG LINE
# =========================================================
def create_points_along_line(line, interval):
    distances = np.arange(0, line.length + interval, interval)
    points = [line.interpolate(d) for d in distances]
    return points, distances

# =========================================================
# 3. GENERATE POINTS FOR EACH LINE FEATURE
# =========================================================
rows = []

for _, row in line_gdf.iterrows():
    line_id = row["id"]  # change if field name differs
    points, dists = create_points_along_line(row.geometry, INTERVAL)

    for pt, dist in zip(points, dists):
        rows.append({
            "line_id": line_id,
            "Distance": dist,
            "geometry": pt
        })

points_gdf = gpd.GeoDataFrame(rows, crs=line_gdf.crs)

# =========================================================
# 4. EASTING / NORTHING
# =========================================================
points_gdf["Easting"] = points_gdf.geometry.x
points_gdf["Northing"] = points_gdf.geometry.y

points_gdf.head(20)

,line_id,Distance,geometry,Easting,Northing
0,1,0.0,POINT (329938.261 2535991.391),329938.260900,2.535991e+06
1,1,3.0,POINT (329935.883 2535989.561),329935.883347,2.535990e+06
2,1,6.0,POINT (329933.506 2535987.732),329933.505794,2.535988e+06
3,1,9.0,POINT (329931.128 2535985.902),329931.128242,2.535986e+06
4,1,12.0,POINT (329928.751 2535984.073),329928.750689,2.535984e+06
5,1,15.0,POINT (329926.373 2535982.243),329926.373136,2.535982e+06
6,1,18.0,POINT (329923.996 2535980.414),329923.995583,2.535980e+06
7,1,21.0,POINT (329921.618 2535978.584),329921.618031,2.535979e+06
8,1,24.0,POINT (329919.24 2535976.755),329919.240478,2.535977e+06
9,1,27.0,POINT (329916.863 2535974.925),329916.862925,2.535975e+06
10,1,30.0,POINT (329914.485 2535973.096),329914.485372,2.535973e+06
11,1,33.0,POINT (329912.108 2535971.266),329912.107820,2.535971e+06
12,1,36.0,POINT (329909.73 2535969.436),329909.730267,2.535969e+06
13,1,39.0,POINT (329907.353 2535967.607),329907.352714,2.535968e+06
14,1,42.0,POINT (329904.975 2535965.777),329904.975161,2.535966e+06
15,1,45.0,POINT (329902.598 2535963.948),329902.597609,2.535964e+06
16,1,48.0,POINT (329900.22 2535962.118),329900.220056,2.535962e+06
17,1,51.0,POINT (329897.843 2535960.289),329897.842503,2.535960e+06
18,1,54.0,POINT (329895.465 2535958.459),329895.464950,2.535958e+06
19,1,57.0,POINT (329893.087 2535956.63),329893.087398,2.535957e+06

In [30]:
# =========================================================
# 5. BUFFER + SPATIAL JOIN
# =========================================================
buffered = points_gdf.copy()
buffered["geometry"] = buffered.geometry.buffer(BUFFER_DIST)

joined = gpd.sjoin(
    buffered,
    survey_gdf[["RL_mMSL", "geometry"]],
    how="left",
    predicate="intersects"
)

# =========================================================
# 6. SELECT NEAREST SURVEY POINT RL (FINAL & CORRECT)
# =========================================================

def compute_dist(row):
    if pd.isna(row["index_right"]):
        return np.nan
    return row.geometry.centroid.distance(
        survey_gdf.loc[row["index_right"]].geometry
    )

# Compute distance safely
joined["dist"] = joined.apply(compute_dist, axis=1)

# Sort by distance (nearest first)
joined = joined.sort_values("dist")

# IMPORTANT: group by ORIGINAL thalweg point index
nearest_rl = (
    joined
    .groupby(joined.index)
    .first()["RL_mMSL"]
)

# Assign back
points_gdf["RLmMSL"] = nearest_rl

points_gdf.head(50)

,line_id,Distance,geometry,Easting,Northing,RLmMSL
0,1,0.0,POINT (329938.261 2535991.391),329938.260900,2.535991e+06,-1.63
1,1,3.0,POINT (329935.883 2535989.561),329935.883347,2.535990e+06,NaN
2,1,6.0,POINT (329933.506 2535987.732),329933.505794,2.535988e+06,NaN
3,1,9.0,POINT (329931.128 2535985.902),329931.128242,2.535986e+06,NaN
4,1,12.0,POINT (329928.751 2535984.073),329928.750689,2.535984e+06,NaN
5,1,15.0,POINT (329926.373 2535982.243),329926.373136,2.535982e+06,NaN
6,1,18.0,POINT (329923.996 2535980.414),329923.995583,2.535980e+06,NaN
7,1,21.0,POINT (329921.618 2535978.584),329921.618031,2.535979e+06,NaN
8,1,24.0,POINT (329919.24 2535976.755),329919.240478,2.535977e+06,NaN
9,1,27.0,POINT (329916.863 2535974.925),329916.862925,2.535975e+06,NaN
10,1,30.0,POINT (329914.485 2535973.096),329914.485372,2.535973e+06,NaN
11,1,33.0,POINT (329912.108 2535971.266),329912.107820,2.535971e+06,NaN
12,1,36.0,POINT (329909.73 2535969.436),329909.730267,2.535969e+06,NaN
13,1,39.0,POINT (329907.353 2535967.607),329907.352714,2.535968e+06,NaN
14,1,42.0,POINT (329904.975 2535965.777),329904.975161,2.535966e+06,NaN
15,1,45.0,POINT (329902.598 2535963.948),329902.597609,2.535964e+06,NaN
16,1,48.0,POINT (329900.22 2535962.118),329900.220056,2.535962e+06,NaN
17,1,51.0,POINT (329897.843 2535960.289),329897.842503,2.535960e+06,NaN
18,1,54.0,POINT (329895.465 2535958.459),329895.464950,2.535958e+06,NaN
19,1,57.0,POINT (329893.087 2535956.63),329893.087398,2.535957e+06,NaN
20,1,60.0,POINT (329890.71 2535954.8),329890.709845,2.535955e+06,NaN
21,1,63.0,POINT (329888.332 2535952.971),329888.332292,2.535953e+06,NaN
22,1,66.0,POINT (329885.955 2535951.141),329885.954739,2.535951e+06,NaN
23,1,69.0,POINT (329883.577 2535949.311),329883.577187,2.535949e+06,NaN
24,1,72.0,POINT (329881.2 2535947.482),329881.199634,2.535947e+06,NaN
25,1,75.0,POINT (329878.822 2535945.652),329878.822081,2.535946e+06,NaN
26,1,78.0,POINT (329876.445 2535943.823),329876.444528,2.535944e+06,NaN
27,1,81.0,POINT (329874.067 2535941.993),329874.066976,2.535942e+06,NaN
28,1,84.0,POINT (329871.689 2535940.164),329871.689423,2.535940e+06,NaN
29,1,87.0,POINT (329869.312 2535938.334),329869.311870,2.535938e+06,NaN
30,1,90.0,POINT (329866.934 2535936.505),329866.934317,2.535937e+06,NaN
31,1,93.0,POINT (329864.557 2535934.675),329864.556765,2.535935e+06,NaN
32,1,96.0,POINT (329862.179 2535932.845),329862.179212,2.535933e+06,NaN
33,1,99.0,POINT (329859.802 2535931.016),329859.801659,2.535931e+06,NaN
34,1,102.0,POINT (329857.424 2535929.186),329857.424106,2.535929e+06,NaN
35,1,105.0,POINT (329855.047 2535927.357),329855.046554,2.535927e+06,NaN
36,1,108.0,POINT (329852.669 2535925.527),329852.669001,2.535926e+06,NaN
37,1,111.0,POINT (329850.291 2535923.698),329850.291448,2.535924e+06,NaN
38,1,114.0,POINT (329847.914 2535921.868),329847.913895,2.535922e+06,NaN
39,1,117.0,POINT (329845.536 2535920.039),329845.536343,2.535920e+06,NaN
40,1,120.0,POINT (329843.159 2535918.209),329843.158790,2.535918e+06,NaN
41,1,123.0,POINT (329840.781 2535916.38),329840.781237,2.535916e+06,NaN
42,1,126.0,POINT (329838.404 2535914.55),329838.403684,2.535915e+06,NaN
43,1,129.0,POINT (329836.026 2535912.72),329836.026132,2.535913e+06,NaN
44,1,132.0,POINT (329833.649 2535910.891),329833.648579,2.535911e+06,NaN
45,1,135.0,POINT (329831.271 2535909.061),329831.271026,2.535909e+06,NaN
46,1,138.0,POINT (329828.893 2535907.232),329828.893473,2.535907e+06,NaN
47,1,141.0,POINT (329826.516 2535905.402),329826.515921,2.535905e+06,NaN
48,1,144.0,POINT (329824.138 2535903.573),329824.138368,2.535904e+06,NaN
49,1,147.0,POINT (329821.761 2535901.743),329821.760815,2.535902e+06,NaN

In [31]:
# =========================================================
# 7. CONTROLLED INTERPOLATION (NO EXTRAPOLATION)
# =========================================================
points_gdf.sort_values(["line_id", "Distance"], inplace=True)

points_gdf["RLmMSL"] = (
    points_gdf
    .groupby("line_id")["RLmMSL"]
    .transform(lambda s: s.interpolate(method="linear", limit_area="inside"))
)

print("✅ PROCESS COMPLETED SUCCESSFULLY")

points_gdf.head(20)

✅ PROCESS COMPLETED SUCCESSFULLY

,line_id,Distance,geometry,Easting,Northing,RLmMSL
0,1,0.0,POINT (329938.261 2535991.391),329938.260900,2.535991e+06,-1.630000
1,1,3.0,POINT (329935.883 2535989.561),329935.883347,2.535990e+06,-1.626970
2,1,6.0,POINT (329933.506 2535987.732),329933.505794,2.535988e+06,-1.623939
3,1,9.0,POINT (329931.128 2535985.902),329931.128242,2.535986e+06,-1.620909
4,1,12.0,POINT (329928.751 2535984.073),329928.750689,2.535984e+06,-1.617879
5,1,15.0,POINT (329926.373 2535982.243),329926.373136,2.535982e+06,-1.614848
6,1,18.0,POINT (329923.996 2535980.414),329923.995583,2.535980e+06,-1.611818
7,1,21.0,POINT (329921.618 2535978.584),329921.618031,2.535979e+06,-1.608788
8,1,24.0,POINT (329919.24 2535976.755),329919.240478,2.535977e+06,-1.605758
9,1,27.0,POINT (329916.863 2535974.925),329916.862925,2.535975e+06,-1.602727
10,1,30.0,POINT (329914.485 2535973.096),329914.485372,2.535973e+06,-1.599697
11,1,33.0,POINT (329912.108 2535971.266),329912.107820,2.535971e+06,-1.596667
12,1,36.0,POINT (329909.73 2535969.436),329909.730267,2.535969e+06,-1.593636
13,1,39.0,POINT (329907.353 2535967.607),329907.352714,2.535968e+06,-1.590606
14,1,42.0,POINT (329904.975 2535965.777),329904.975161,2.535966e+06,-1.587576
15,1,45.0,POINT (329902.598 2535963.948),329902.597609,2.535964e+06,-1.584545
16,1,48.0,POINT (329900.22 2535962.118),329900.220056,2.535962e+06,-1.581515
17,1,51.0,POINT (329897.843 2535960.289),329897.842503,2.535960e+06,-1.578485
18,1,54.0,POINT (329895.465 2535958.459),329895.464950,2.535958e+06,-1.575455
19,1,57.0,POINT (329893.087 2535956.63),329893.087398,2.535957e+06,-1.572424

In [32]:
# =========================================================
# 8. SAVE OUTPUT
# =========================================================
points_gdf.to_file(OUTPUT_FILE, driver="GeoJSON")