In [8]:
import pandas as pd
import os

folder_path = r"F:\P-529990 Joydeppur Iswardi Double Rail Line\CS Section Data Khal"

data_df = {}   # dictionary to store all DataFrames

for file in os.listdir(folder_path):
    if file.lower().endswith(".xlsm"):
        base_name = os.path.splitext(file)[0]   # automatic key
        file_path = os.path.join(folder_path, file)

        data_df[base_name] = pd.read_excel(
            file_path,
            engine="openpyxl"
        )

print(data_df.keys())

dict_keys(['CS_Bangali', 'CS_Bangshi', 'CS_Baral', 'CS_Gumni', 'CS_Khal9_final', 'CS_Khal_1_final', 'CS_Khal_2', 'CS_Khal_3', 'CS_Khal_4_final', 'CS_khal_6', 'CS_Khal_7_final', 'CS_Khal_8_final', 'CS_Pungli_River_Final', 'CS_Turag_Final_2'])

In [15]:
for name, df in data_df.items():
    print(name)
    display(df.head())

CS_Bangali

,SL No.,Chainage,Easting,Northing,Distance,Elevation,Description
0,1.0,0.0,763387.8380,2693810.498,0.000000,11.314,Cemetery
1,2.0,0.0,763386.7200,2693815.144,4.778623,11.366,Cemetery
2,3.0,0.0,763384.1814,2693822.398,12.449125,11.243,Cemetery B.wall
3,4.0,0.0,763382.7400,2693826.320,16.623035,11.141,Cemetery B.wall
4,5.0,0.0,763381.9580,2693827.765,18.240715,11.250,Cc block

CS_Bangshi

,SL No.,Name,Section ID,Easting,Northing,Distance,RL_m MSL,Description
0,1.0,Bangshi River,1.0,216609.523,2666224.134,0.0,8.683,PR
1,2.0,Bangshi River,1.0,216603.441,2666224.756,28.0,8.459,PR
2,3.0,Bangshi River,1.0,216601.420,2666225.203,29.0,8.287,LB
3,4.0,Bangshi River,1.0,216600.606,2666225.191,30.0,8.107,slope
4,5.0,Bangshi River,1.0,216599.731,2666225.474,31.0,7.652,slope

CS_Baral

    SL   Name  Section_ID   Easting   Northing  Distance  RL_m_MSL Remarks
0  1.0  Baral         1.0  737141.0  2682010.0       0.0    10.033    LAND
1  2.0  Baral         1.0  737138.0  2682005.0       5.0     9.991    LAND
2  3.0  Baral         1.0  737135.0  2682000.0      11.0    10.149    LAND
3  4.0  Baral         1.0  737132.0  2681996.0      16.0    10.174    LAND
4  5.0  Baral         1.0  737130.0  2681992.0      21.0    10.125    LAND

CS_Gumni

   SL No Chainage   Easting   Northing   Distance  RL_m_MSL Remarks
0    1.0        0  740415.0  2683474.0   0.000000     9.716    Land
1    2.0        0  740411.0  2683466.0   8.944272     9.672    Land
2    3.0        0  740409.0  2683460.0  15.231546     9.693    Land
3    4.0        0  740406.0  2683454.0  21.931712     9.659    Land
4    5.0        0  740404.0  2683447.0  29.154759     9.641    Land

CS_Khal9_final

   SL No.  Chainage     Easting     Northing   Distance  RL_m_MSL   Remarks
0     1.0       0.0  226704.336  2659574.387   0.000000     8.081  HBB Road
1     2.0       0.0  226687.101  2659577.388  17.494320     7.908  HBB Road
2     3.0       0.0  226675.356  2659578.972  29.340461     7.599  HBB Road
3     4.0       0.0  226668.553  2659580.168  36.246973     7.616  HBB Road
4     5.0       0.0  226667.591  2659580.504  37.250674     6.968     slope

CS_Khal_1_final

   SL No.  Section_ID     Easting     Northing  Distance      RL Remarks
0     1.0         1.0  726296.833  2675835.922  0.000000  12.191      HS
1     2.0         1.0  726297.119  2675835.329  0.658365  12.096      HS
2     3.0         1.0  726298.737  2675832.657  3.779609  12.108      HS
3     4.0         1.0  726299.042  2675831.844  4.637862  12.374      HS
4     5.0         1.0  726300.592  2675829.294  7.619742  12.090      HS

CS_Khal_2

   SL No.  Section_ID       Easting      Northing   Distance  RL_m_MSL Remarks
0     1.0         1.0  749705.71601  2.682108e+06   0.000000     7.626    Land
1     2.0         1.0  749703.60701  2.682108e+06   2.151199     7.599    Land
2     3.0         1.0  749699.66201  2.682108e+06   6.064873     7.538    Land
3     4.0         1.0  749696.89801  2.682108e+06   8.826141     7.568    Land
4     5.0         1.0  749693.80201  2.682108e+06  11.919529     7.524    Land

CS_Khal_3

   SL No.  Section_ID     Easting     Northing  Distance      RL   Remarks
0     1.0         1.0  752821.078  2683895.483  0.000000  11.676  h/s area
1     2.0         1.0  752817.202  2683893.789  4.230013  11.387  h/s area
2     3.0         1.0  752814.752  2683892.612  6.000000  11.238        LB
3     4.0         1.0  752814.644  2683892.697  7.011287  11.191     slope
4     5.0         1.0  752812.933  2683892.231  8.770207  10.871     slope

CS_Khal_4_final

   SL No.  Chainage     Easting     Northing  Distance  RL_m_MSL    Remarks
0     1.0       0.0  759942.121  2690277.650  0.000000    12.243         PR
1     2.0       0.0  759941.021  2690278.390  1.325745    12.274         PR
2     3.0       0.0  759939.661  2690279.266  2.943307    12.062         PR
3     4.0       0.0  759938.801  2690280.070  4.108382    12.379  HSvB wall
4     5.0       0.0  759938.344  2690280.441  4.696319    12.422         HS

CS_khal_6

   SL No.  Chainage        Easting      Northing  Distance     RL Remarks
0     1.0       1.0  209463.793005  2.668502e+06  0.000000  9.320      HS
1     2.0       1.0  209464.328005  2.668502e+06  0.535681  9.115      ER
2     3.0       1.0  209467.047005  2.668502e+06  3.260833  8.991      ER
3     4.0       1.0  209468.041006  2.668502e+06  4.258510  8.572   slope
4     5.0       1.0  209469.652006  2.668501e+06  5.909120  7.811    land

CS_Khal_7_final

   SL No.  Chainage     Easting     Northing  Distance     RL   Remarks
0     1.0       0.0  216055.684  2666122.936  0.000000  7.848       h/s
1     2.0       0.0  216054.038  2666124.138  2.038166  7.956  h/s area
2     3.0       0.0  216051.194  2666124.593  4.785995  8.008  h/s area
3     4.0       0.0  216049.055  2666125.657  7.165716  8.108      Bank
4     5.0       0.0  216048.355  2666126.091  7.979240  7.687     slope

CS_Khal_8_final

,SL No.,Chainage,Easting,Northing,Distance,RL_m_MSL,Remarks
0,1.0,0.0,222670.841842,2.663539e+06,0.000000,3.99,paddy land
1,2.0,0.0,222660.924626,2.663537e+06,10.060374,4.04,paddy land
2,3.0,0.0,222651.007409,2.663536e+06,20.120748,4.07,paddy land
3,4.0,0.0,222646.048802,2.663535e+06,25.151018,4.09,RB
4,5.0,0.0,222644.065378,2.663535e+06,27.163007,2.99,Sounding

CS_Pungli_River_Final

,SL No.,Chainage,Name,Easting,Northing,Distance,RL_m MSL,Remarks
0,1.0,0.0,Pungli River,794442.0,2695908.338,0.0,12.726,mango garden
1,2.0,0.0,Pungli River,794441.0,2695897.496,11.0,12.829,mango garden
2,3.0,0.0,Pungli River,794439.0,2695884.033,25.0,12.699,mango garden
3,4.0,0.0,Pungli River,794437.0,2695878.571,30.0,12.628,mango garden
4,5.0,0.0,Pungli River,794436.0,2695877.156,32.0,12.537,LB

CS_Turag_Final_2

,SL No.,Section_ID,Easting,Northing,Distance,RL_m_MSL,Remarks
0,1.0,1.0,229949.0,2660793.0,0.000000,12.621,shoulder
1,2.0,1.0,229948.0,2660799.0,6.082763,12.637,shoulder
2,3.0,1.0,229938.0,2660792.0,11.045361,6.600,shoulder
3,4.0,1.0,229937.0,2660792.0,12.041595,5.967,slope c c block
4,5.0,1.0,229935.0,2660793.0,14.000000,5.180,slope c c block

In [11]:
import os

output_folder = r"F:\P 529990 Joydepur Iswardi Double Rail Line\CS_Min_Elevation_Output"
os.makedirs(output_folder, exist_ok=True)

for name, df in data_df.items():
    
    # group by Chainage and take minimum Elevation
    min_elev_df = (
        df.groupby("Chainage", as_index=False)
          .agg({"Elevation": "min"})
    )
    
    # save to Excel (one file per DataFrame)
    output_path = os.path.join(output_folder, f"{name}_min_elevation.xlsx")
    min_elev_df.to_excel(output_path, index=False)

print("✅ Min elevation Excel created for all CS sections")

KeyError: 'Chainage'