In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
wl_df = pd.read_csv(r'E:\MSc RBE\Future Image Generation\WL\SW_91_9_L_Baruria_Transit.csv')
wl_df.head()

   Year  Month  Date            Date.1  WL_mMSL  Unnamed: 5  Unnamed: 6
0  1996      4     1  01/04/1996 06:00     2.73         NaN         NaN
1  1996      4     1  01/04/1996 09:00     2.74         NaN         NaN
2  1996      4     1  01/04/1996 12:00     2.75         NaN         NaN
3  1996      4     1  01/04/1996 15:00     2.76         NaN         NaN
4  1996      4     1  01/04/1996 18:00     2.75         NaN         NaN

In [3]:
# Filter for months December (12), January (1), and February (2)
winter_df = wl_df[wl_df['Month'].isin([12, 1, 2])]

# Group by year and find the minimum WL_mMSL for each year
min_wl_per_year = winter_df.groupby('Year')['WL_mMSL'].min()

print(min_wl_per_year)

Year
1996    2.73
1997    1.89
1998    1.72
1999    1.66
2000    1.51
2001    1.47
2002    1.45
2003    1.43
2004    1.81
2005    1.59
2006    1.16
2007    1.24
2008    1.37
2009    1.73
2010    1.26
2011    1.67
2012    1.74
2013    1.71
2014    1.72
2015    1.54
2016    1.69
2017    1.66
2018    1.68
2019    1.67
2020    1.63
2021    1.43
2022    1.63
Name: WL_mMSL, dtype: float64

In [7]:
# Create a DataFrame with all dates where WL_mMSL is between 1.75 and 2.25, grouped by year

wl_range_df = winter_df[(winter_df['WL_mMSL'] >= 1.75) & (winter_df['WL_mMSL'] <= 2.25)]
dates_in_range_df = wl_range_df.groupby('Year').agg({'Date.1': list}).reset_index()
dates_in_range_df.head(25)

    Year                                             Date.1
0   1997  [21/01/1997 06:00, 21/01/1997 09:00, 21/01/199...
1   1998  [27/01/1998 06:00, 27/01/1998 09:00, 27/01/199...
2   1999  [26/01/1999 06:00, 26/01/1999 09:00, 26/01/199...
3   2000  [15/01/2000 12:00, 15/01/2000 15:00, 15/01/200...
4   2001  [01/01/2001 06:00, 01/01/2001 09:00, 01/01/200...
5   2002  [01/01/2002 06:00, 01/01/2002 09:00, 01/01/200...
6   2003  [01/01/2003 06:00, 01/01/2003 09:00, 01/01/200...
7   2004  [26/01/2004 06:00, 26/01/2004 09:00, 26/01/200...
8   2005  [05/01/2005 15:00, 05/01/2005 18:00, 06/01/200...
9   2006  [01/01/2006 06:00, 01/01/2006 09:00, 01/01/200...
10  2007  [01/01/2007 06:00, 01/01/2007 09:00, 01/01/200...
11  2008  [01/01/2008 06:00, 01/01/2008 09:00, 01/01/200...
12  2009  [15/01/2009 18:00, 16/01/2009 06:00, 16/01/200...
13  2010  [01/01/2010 06:00, 01/01/2010 09:00, 01/01/201...
14  2011  [12/01/2011 18:00, 13/01/2011 06:00, 13/01/201...
15  2012  [17/01/2012 15:00, 17/01/2012 18:00, 18/01/201...
16  2013  [10/01/2013 06:00, 10/01/2013 09:00, 10/01/201...
17  2014  [09/01/2014 12:00, 09/01/2014 15:00, 09/01/201...
18  2015  [12/01/2015 06:00, 12/01/2015 09:00, 12/01/201...
19  2016  [04/01/2016 06:00, 04/01/2016 09:00, 04/01/201...
20  2017  [12/01/2017 06:00, 12/01/2017 09:00, 12/01/201...
21  2018  [11/01/2018 06:00, 11/01/2018 09:00, 11/01/201...
22  2019  [12/01/2019 18:00, 13/01/2019 06:00, 13/01/201...
23  2020  [18/01/2020 09:00, 18/01/2020 12:00, 18/01/202...
24  2021  [08/01/2021 15:00, 08/01/2021 18:00, 09/01/202...

In [8]:
wl_range_df['Date_only'] = wl_range_df['Date.1'].str.split(' ').str[0]
dates_only_in_range_df = wl_range_df.groupby('Year').agg({'Date_only': lambda x: sorted(set(x))}).reset_index()
dates_only_in_range_df.head(25)

C:\Users\rbe\AppData\Local\Temp\ipykernel_14884\2778827805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wl_range_df['Date_only'] = wl_range_df['Date.1'].str.split(' ').str[0]

    Year                                          Date_only
0   1997  [01/02/1997, 02/02/1997, 03/02/1997, 04/02/199...
1   1998  [01/02/1998, 02/02/1998, 03/02/1998, 04/02/199...
2   1999  [01/02/1999, 02/02/1999, 03/02/1999, 04/02/199...
3   2000  [01/02/2000, 02/02/2000, 03/02/2000, 04/02/200...
4   2001  [01/01/2001, 02/01/2001, 03/01/2001, 04/01/200...
5   2002  [01/01/2002, 01/02/2002, 02/01/2002, 02/02/200...
6   2003  [01/01/2003, 02/01/2003, 03/01/2003, 04/01/200...
7   2004  [01/02/2004, 02/02/2004, 03/02/2004, 04/02/200...
8   2005  [01/02/2005, 02/02/2005, 03/02/2005, 05/01/200...
9   2006  [01/01/2006, 02/01/2006, 03/01/2006, 04/01/200...
10  2007  [01/01/2007, 02/01/2007, 03/01/2007, 04/01/200...
11  2008  [01/01/2008, 02/01/2008, 03/01/2008, 04/01/200...
12  2009  [01/02/2009, 02/02/2009, 03/02/2009, 04/02/200...
13  2010  [01/01/2010, 01/02/2010, 02/01/2010, 03/01/201...
14  2011  [01/02/2011, 02/02/2011, 03/02/2011, 04/02/201...
15  2012  [01/02/2012, 02/02/2012, 03/02/2012, 04/02/201...
16  2013  [01/02/2013, 02/02/2013, 03/02/2013, 04/02/201...
17  2014  [01/02/2014, 02/02/2014, 03/02/2014, 04/02/201...
18  2015  [01/02/2015, 02/02/2015, 03/02/2015, 04/02/201...
19  2016  [01/02/2016, 02/02/2016, 03/02/2016, 04/01/201...
20  2017  [01/02/2017, 02/02/2017, 03/02/2017, 04/02/201...
21  2018  [01/02/2018, 02/02/2018, 03/02/2018, 04/02/201...
22  2019  [01/02/2019, 02/02/2019, 03/02/2019, 04/02/201...
23  2020  [01/02/2020, 02/02/2020, 03/02/2020, 04/02/202...
24  2021  [01/02/2021, 02/02/2021, 03/02/2021, 04/02/202...